// Archetype chains — multi-discipline achievement paths.
// Steps use check() functions that need live profile/PR/workout data, so this is exported
// as a factory function rather than a static array — call it fresh with current state
// each time (see index.html call sites), never cache the result across renders.
export function getArchetypeChains({ profile, myPRs, currentUser, myWorkouts, getExerciseSessionCount }) {
  return [
  {
    id:'iron_sovereign',
    name:'Iron Sovereign',
    icon:'⚔️',
    color:'#D4A017',
    desc:'Master the iron. Pure strength dominance.',
    steps:[
      { name:'Bench Press 1× bodyweight',       check:(bw)=>{ const m=profile.bodyType==='female'?0.7:1.0;   return myPRs['Bench Press']?.e1rm >= bw*m; },    label:(bw)=>{ const m=profile.bodyType==='female'?0.7:1.0;   return `Bench Press ${m}× bodyweight (${Math.round(bw*m)}kg)`; } },
      { name:'Squat 1.5× bodyweight',           check:(bw)=>{ const m=profile.bodyType==='female'?1.1:1.5;   return myPRs['Squat']?.e1rm >= bw*m; },          label:(bw)=>{ const m=profile.bodyType==='female'?1.1:1.5;   return `Squat ${m}× bodyweight (${Math.round(bw*m)}kg)`; } },
      { name:'Deadlift 2× bodyweight',          check:(bw)=>{ const m=profile.bodyType==='female'?1.5:2.0;   return myPRs['Deadlift']?.e1rm >= bw*m; },        label:(bw)=>{ const m=profile.bodyType==='female'?1.5:2.0;   return `Deadlift ${m}× bodyweight (${Math.round(bw*m)}kg)`; } },
      { name:'Overhead Press 0.75× bodyweight', check:(bw)=>{ const m=profile.bodyType==='female'?0.5:0.75;  return myPRs['Overhead Press']?.e1rm >= bw*m; },  label:(bw)=>{ const m=profile.bodyType==='female'?0.5:0.75;  return `OHP ${m}× bodyweight (${Math.round(bw*m)}kg)`; } },
      { name:'Bench Press 1.5× bodyweight',     check:(bw)=>{ const m=profile.bodyType==='female'?1.0:1.5;   return myPRs['Bench Press']?.e1rm >= bw*m; },    label:(bw)=>{ const m=profile.bodyType==='female'?1.0:1.5;   return `Bench Press ${m}× bodyweight (${Math.round(bw*m)}kg)`; } },
      { name:'Squat 2× bodyweight',             check:(bw)=>{ const m=profile.bodyType==='female'?1.5:2.0;   return myPRs['Squat']?.e1rm >= bw*m; },          label:(bw)=>{ const m=profile.bodyType==='female'?1.5:2.0;   return `Squat ${m}× bodyweight (${Math.round(bw*m)}kg)`; } },
      { name:'Deadlift 2.5× bodyweight',        check:(bw)=>{ const m=profile.bodyType==='female'?1.85:2.5;  return myPRs['Deadlift']?.e1rm >= bw*m; },        label:(bw)=>{ const m=profile.bodyType==='female'?1.85:2.5;  return `Deadlift ${m}× bodyweight (${Math.round(bw*m)}kg)`; } },
    ],
    title:'[Iron Sovereign]',
  },
  {
    id:'shadow_athlete',
    name:'Shadow Athlete',
    icon:'🐉',
    color:'#9B59B6',
    desc:'Master your own body. The iron needs no bar.',
    steps:[
      { name:'Muscle Up (5 sessions)',                 check:()=>getExerciseSessionCount('Muscle Up', currentUser.uid)>=5 },
      { name:'Tuck Planche (3 sessions)',              check:()=>getExerciseSessionCount('Tuck Planche', currentUser.uid)>=3 },
      { name:'Tuck Front Lever (3 sessions)',          check:()=>getExerciseSessionCount('Tuck Front Lever', currentUser.uid)>=3 },
      { name:'Advanced Tuck Planche (3 sessions)',     check:()=>getExerciseSessionCount('Advanced Tuck Planche', currentUser.uid)>=3 },
      { name:'Straddle Front Lever (3 sessions)',      check:()=>getExerciseSessionCount('Straddle Front Lever', currentUser.uid)>=3 },
      { name:'Straddle Planche (3 sessions)',          check:()=>getExerciseSessionCount('Straddle Planche', currentUser.uid)>=3 },
      { name:'Full Planche (3 sessions)',              check:()=>getExerciseSessionCount('Full Planche', currentUser.uid)>=3 },
      { name:'Front Lever (3 sessions)',               check:()=>getExerciseSessionCount('Front Lever', currentUser.uid)>=3 },
    ],
    title:'[Shadow Athlete]',
  },
  {
    id:'endurance_wraith',
    name:'Endurance Wraith',
    icon:'🌪️',
    color:'#1ABC9C',
    desc:'Distance is not your enemy. It never was.',
    steps:[
      { name:'Log first run',            check:()=>myWorkouts.some(w=>w.isRun) },
      { name:'Run 5km',                  check:()=>myWorkouts.some(w=>w.runSummary?.distKm>=5) },
      { name:'Run 10km',                 check:()=>myWorkouts.some(w=>w.runSummary?.distKm>=10) },
      { name:'Sub-30 min 5km',           check:()=>{ const t=profile.bodyType==='female'?34:30; return myWorkouts.some(w=>{ const r=w.runSummary; return r&&r.distKm>=4.9&&r.durationMins<=t; }); }, label:()=>`Sub-${profile.bodyType==='female'?34:30} min 5km` },
      { name:'Run half marathon (21km)', check:()=>myWorkouts.some(w=>w.runSummary?.distKm>=21) },
      { name:'Sub-60 min 10km',          check:()=>{ const t=profile.bodyType==='female'?68:60; return myWorkouts.some(w=>{ const r=w.runSummary; return r&&r.distKm>=9.9&&r.durationMins<=t; }); }, label:()=>`Sub-${profile.bodyType==='female'?68:60} min 10km` },
      { name:'Sub-2hr half marathon',    check:()=>{ const t=profile.bodyType==='female'?135:120; return myWorkouts.some(w=>{ const r=w.runSummary; return r&&r.distKm>=21&&r.durationMins<=t; }); }, label:()=>`Sub-${profile.bodyType==='female'?'2hr 15min':'2hr'} half marathon` },
      { name:'Run full marathon (42km)', check:()=>myWorkouts.some(w=>w.runSummary?.distKm>=42) },
    ],
    title:'[Endurance Wraith]',
  },
  {
    id:'assassin',
    name:'Assassin',
    icon:'⚡',
    color:'#F0D000',
    desc:'Speed is the only truth. Explosive, reactive, lethal.',
    steps:[
      { name:'Box Jump (5 sessions)',          check:()=>getExerciseSessionCount('Box Jump', currentUser.uid)>=5 },
      { name:'Jump Squat (5 sessions)',        check:()=>getExerciseSessionCount('Jump Squat', currentUser.uid)>=5 },
      { name:'Hill Sprints (5 sessions)',      check:()=>getExerciseSessionCount('Hill Sprints', currentUser.uid)>=5 },
      { name:'Interval Running (5 sessions)', check:()=>getExerciseSessionCount('Interval Running', currentUser.uid)>=5 },
      { name:'Tempo Run (5 sessions)',         check:()=>getExerciseSessionCount('Tempo Run', currentUser.uid)>=5 },
      { name:'Elite 5km time',                check:()=>{ const t=profile.bodyType==='female'?28:25; return myWorkouts.some(w=>{ const r=w.runSummary; return r&&r.distKm>=4.9&&r.durationMins<=t; }); }, label:()=>`Sub-${profile.bodyType==='female'?28:25} min 5km` },
    ],
    title:'[Assassin]',
  },
  {
    id:'hybrid_sovereign',
    name:'Hybrid Sovereign',
    icon:'⚖️',
    color:'#3DA5FF',
    desc:'Iron and bodyweight. Both bend to you.',
    steps:[
      { name:'Deadlift 1.5× bodyweight',     check:(bw)=>{ const m=profile.bodyType==='female'?1.1:1.5;  return myPRs['Deadlift']?.e1rm >= bw*m; },    label:(bw)=>{ const m=profile.bodyType==='female'?1.1:1.5;  return `Deadlift ${m}× bodyweight (${Math.round(bw*m)}kg)`; } },
      { name:'Pull Up (10 sessions)',         check:()=>getExerciseSessionCount('Pull Up', currentUser.uid)>=10 },
      { name:'Bench Press 1.25× bodyweight', check:(bw)=>{ const m=profile.bodyType==='female'?0.85:1.25; return myPRs['Bench Press']?.e1rm >= bw*m; }, label:(bw)=>{ const m=profile.bodyType==='female'?0.85:1.25; return `Bench Press ${m}× bodyweight (${Math.round(bw*m)}kg)`; } },
      { name:'Muscle Up (5 sessions)',        check:()=>getExerciseSessionCount('Muscle Up', currentUser.uid)>=5 },
      { name:'Squat 1.5× bodyweight',        check:(bw)=>{ const m=profile.bodyType==='female'?1.1:1.5;  return myPRs['Squat']?.e1rm >= bw*m; },       label:(bw)=>{ const m=profile.bodyType==='female'?1.1:1.5;  return `Squat ${m}× bodyweight (${Math.round(bw*m)}kg)`; } },
      { name:'Tuck Planche (3 sessions)',     check:()=>getExerciseSessionCount('Tuck Planche', currentUser.uid)>=3 },
      { name:'Deadlift 2× bodyweight',       check:(bw)=>{ const m=profile.bodyType==='female'?1.5:2.0;  return myPRs['Deadlift']?.e1rm >= bw*m; },    label:(bw)=>{ const m=profile.bodyType==='female'?1.5:2.0;  return `Deadlift ${m}× bodyweight (${Math.round(bw*m)}kg)`; } },
      { name:'Front Lever (3 sessions)',      check:()=>getExerciseSessionCount('Front Lever', currentUser.uid)>=3 },
    ],
    title:'[Hybrid Sovereign]',
  },
  {
    id:'ranger',
    name:'Ranger',
    icon:'🏹',
    color:'#2ECC71',
    desc:'Road and iron. Neither owns you. Both serve you.',
    steps:[
      { name:'Deadlift 1× bodyweight',       check:(bw)=>{ const m=profile.bodyType==='female'?0.75:1.0; return myPRs['Deadlift']?.e1rm >= bw*m; },   label:(bw)=>{ const m=profile.bodyType==='female'?0.75:1.0; return `Deadlift ${m}× bodyweight (${Math.round(bw*m)}kg)`; } },
      { name:'Run 5km',                      check:()=>myWorkouts.some(w=>w.runSummary?.distKm>=5) },
      { name:'Squat 1× bodyweight',          check:(bw)=>{ const m=profile.bodyType==='female'?0.75:1.0; return myPRs['Squat']?.e1rm >= bw*m; },      label:(bw)=>{ const m=profile.bodyType==='female'?0.75:1.0; return `Squat ${m}× bodyweight (${Math.round(bw*m)}kg)`; } },
      { name:'Sub-30 min 5km',               check:()=>{ const t=profile.bodyType==='female'?34:30; return myWorkouts.some(w=>{ const r=w.runSummary; return r&&r.distKm>=4.9&&r.durationMins<=t; }); }, label:()=>`Sub-${profile.bodyType==='female'?34:30} min 5km` },
      { name:'Bench Press 1× bodyweight',    check:(bw)=>{ const m=profile.bodyType==='female'?0.7:1.0;  return myPRs['Bench Press']?.e1rm >= bw*m; }, label:(bw)=>{ const m=profile.bodyType==='female'?0.7:1.0;  return `Bench Press ${m}× bodyweight (${Math.round(bw*m)}kg)`; } },
      { name:'Run 10km',                     check:()=>myWorkouts.some(w=>w.runSummary?.distKm>=10) },
      { name:'Deadlift 1.5× bodyweight',     check:(bw)=>{ const m=profile.bodyType==='female'?1.1:1.5;  return myPRs['Deadlift']?.e1rm >= bw*m; },   label:(bw)=>{ const m=profile.bodyType==='female'?1.1:1.5;  return `Deadlift ${m}× bodyweight (${Math.round(bw*m)}kg)`; } },
      { name:'Sub-60 min 10km',              check:()=>{ const t=profile.bodyType==='female'?68:60; return myWorkouts.some(w=>{ const r=w.runSummary; return r&&r.distKm>=9.9&&r.durationMins<=t; }); }, label:()=>`Sub-${profile.bodyType==='female'?68:60} min 10km` },
    ],
    title:'[Ranger]',
  },
  {
    id:'warlord',
    name:'Warlord',
    icon:'🏛️',
    color:'#D4A017',
    desc:'Volume is the language of dominance. High sets, relentless reps, maximal hypertrophy.',
    steps:[
      { name:'Log 50 total workouts',                    check:()=>myWorkouts.length>=50 },
      { name:'Bench Press — Novice tier PR',             check:()=>['Novice','Intermediate','Advanced','Elite'].includes(myPRs['Bench Press']?.tier) },
      { name:'Squat — Novice tier PR',                   check:()=>['Novice','Intermediate','Advanced','Elite'].includes(myPRs['Squat']?.tier) },
      { name:'Log 100 total workouts',                   check:()=>myWorkouts.length>=100 },
      { name:'Bench Press — Intermediate tier PR',       check:()=>['Intermediate','Advanced','Elite'].includes(myPRs['Bench Press']?.tier) },
      { name:'Squat — Intermediate tier PR',             check:()=>['Intermediate','Advanced','Elite'].includes(myPRs['Squat']?.tier) },
      { name:'Deadlift — Intermediate tier PR',          check:()=>['Intermediate','Advanced','Elite'].includes(myPRs['Deadlift']?.tier) },
      { name:'Log 200 total workouts',                   check:()=>myWorkouts.length>=200 },
      { name:'Bench Press — Advanced tier PR',           check:()=>['Advanced','Elite'].includes(myPRs['Bench Press']?.tier) },
      { name:'Deadlift — Advanced tier PR',              check:()=>['Advanced','Elite'].includes(myPRs['Deadlift']?.tier) },
    ],
    title:'[Warlord]',
  },
  {
    id:'monk',
    name:'Monk',
    icon:'🧘',
    color:'#A8D8EA',
    desc:'Stillness is its own kind of strength. Control, precision, mastery of movement.',
    steps:[
      { name:'Dead Hang (5 sessions)',                   check:()=>getExerciseSessionCount('Dead Hang', currentUser.uid)>=5 },
      { name:'L-Sit (5 sessions)',                       check:()=>getExerciseSessionCount('L-Sit', currentUser.uid)>=5 },
      { name:'Wall Handstand Hold (5 sessions)',         check:()=>getExerciseSessionCount('Wall Handstand Hold', currentUser.uid)>=5 },
      { name:'Frog Stand (5 sessions)',                  check:()=>getExerciseSessionCount('Frog Stand', currentUser.uid)>=5 },
      { name:'Plank (20 sessions)',                      check:()=>getExerciseSessionCount('Plank', currentUser.uid)>=20 },
      { name:'Freestanding Handstand (5 sessions)',      check:()=>getExerciseSessionCount('Freestanding Handstand Hold', currentUser.uid)>=5 },
      { name:'Tuck Planche (5 sessions)',                check:()=>getExerciseSessionCount('Tuck Planche', currentUser.uid)>=5 },
      { name:'Tuck Front Lever (5 sessions)',            check:()=>getExerciseSessionCount('Tuck Front Lever', currentUser.uid)>=5 },
      { name:'Handstand Push Up (5 sessions)',           check:()=>getExerciseSessionCount('Handstand Push Up', currentUser.uid)>=5 },
      { name:'30-day streak',                            check:()=>computeStreak(currentUser.uid)>=30 },
    ],
    title:'[Monk]',
  },
  {
    id:'striker',
    name:'Striker',
    icon:'🥊',
    color:'#E74C3C',
    desc:'The ring forged you. Combat conditioning defines you.',
    steps:[
      { name:'Boxing — Bag Work (10 sessions)',   check:()=>getExerciseSessionCount('Boxing — Bag Work', currentUser.uid)>=10 },
      { name:'Boxing — Shadow Boxing (10 sessions)', check:()=>getExerciseSessionCount('Boxing — Shadow Boxing', currentUser.uid)>=10 },
      { name:'Boxing — Pad Work (10 sessions)',   check:()=>getExerciseSessionCount('Boxing — Pad Work', currentUser.uid)>=10 },
      { name:'Boxing — Sparring (5 sessions)',    check:()=>getExerciseSessionCount('Boxing — Sparring', currentUser.uid)>=5 },
      { name:'Hill Sprints (10 sessions)',        check:()=>getExerciseSessionCount('Hill Sprints', currentUser.uid)>=10 },
      { name:'50 total boxing sessions',          check:()=>['Boxing — Bag Work','Boxing — Sparring','Boxing — Pad Work','Boxing — Shadow Boxing'].reduce((t,n)=>t+getExerciseSessionCount(n,currentUser.uid),0)>=50 },
    ],
    title:'[Striker]',
  },
  {
    id:'aqua_hunter',
    name:'Aqua Hunter',
    icon:'🌊',
    color:'#2980B9',
    desc:'The water is your domain.',
    steps:[
      { name:'Freestyle Swimming (10 sessions)',    check:()=>getExerciseSessionCount('Freestyle Swimming', currentUser.uid)>=10 },
      { name:'Breaststroke Swimming (5 sessions)',  check:()=>getExerciseSessionCount('Breaststroke Swimming', currentUser.uid)>=5 },
      { name:'Backstroke Swimming (5 sessions)',    check:()=>getExerciseSessionCount('Backstroke Swimming', currentUser.uid)>=5 },
      { name:'Butterfly Swimming (5 sessions)',     check:()=>getExerciseSessionCount('Butterfly Swimming', currentUser.uid)>=5 },
      { name:'Open Water Swimming (3 sessions)',    check:()=>getExerciseSessionCount('Open Water Swimming', currentUser.uid)>=3 },
      { name:'50 total swim sessions',             check:()=>['Freestyle Swimming','Breaststroke Swimming','Backstroke Swimming','Butterfly Swimming','Open Water Swimming','HIIT Swimming'].reduce((t,n)=>t+getExerciseSessionCount(n,currentUser.uid),0)>=50 },
    ],
    title:'[Aqua Hunter]',
  },
  {
    id:'court_king',
    name:'Court King',
    icon:'🏀',
    color:'#F39C12',
    desc:'The arena is your domain. Sport defines your movement.',
    steps:[
      { name:'Basketball (10 sessions)',           check:()=>getExerciseSessionCount('Basketball', currentUser.uid)>=10 },
      { name:'Tennis (10 sessions)',               check:()=>getExerciseSessionCount('Tennis', currentUser.uid)>=10 },
      { name:'Football — Soccer (10 sessions)',    check:()=>getExerciseSessionCount('Football (Soccer)', currentUser.uid)>=10 },
      { name:'50 total sport sessions',            check:()=>['Tennis','Tennis Drills','Basketball','Basketball Drills','Football (Soccer)','Football Drills','American Football'].reduce((t,n)=>t+getExerciseSessionCount(n,currentUser.uid),0)>=50 },
      { name:'Bench Press 1× bodyweight',          check:(bw)=>{ const m=profile.bodyType==='female'?0.7:1.0; return myPRs['Bench Press']?.e1rm >= bw*m; }, label:(bw)=>{ const m=profile.bodyType==='female'?0.7:1.0; return `Bench Press ${m}× bodyweight (${Math.round(bw*m)}kg)`; } },
    ],
    title:'[Court King]',
  },
  {
    id:'alpinist',
    name:'Alpinist',
    icon:'🏔️',
    color:'#27AE60',
    desc:'The summit does not care about your excuses.',
    steps:[
      { name:'Bouldering (10 sessions)',           check:()=>getExerciseSessionCount('Bouldering', currentUser.uid)>=10 },
      { name:'Top Rope Climbing (5 sessions)',     check:()=>getExerciseSessionCount('Top Rope Climbing', currentUser.uid)>=5 },
      { name:'Sport Climbing (10 sessions)',       check:()=>getExerciseSessionCount('Sport Climbing', currentUser.uid)>=10 },
      { name:'Traditional Climbing (5 sessions)', check:()=>getExerciseSessionCount('Traditional Climbing', currentUser.uid)>=5 },
      { name:'German Hang (10 sessions)',          check:()=>getExerciseSessionCount('German Hang', currentUser.uid)>=10 },
      { name:'Front Splits (5 sessions)',          check:()=>getExerciseSessionCount('Front Splits', currentUser.uid)>=5 },
      { name:'50 total climbing sessions',         check:()=>['Bouldering','Sport Climbing','Top Rope Climbing','Traditional Climbing'].reduce((t,n)=>t+getExerciseSessionCount(n,currentUser.uid),0)>=50 },
    ],
    title:'[Alpinist]',
  },
  {
    id:'sovereign_flex',
    name:'Sovereign of Mobility',
    icon:'🌊',
    color:'#E8D5B7',
    desc:'Range of motion is power most hunters never develop.',
    steps:[
      { name:'Front Splits (10 sessions)',                check:()=>getExerciseSessionCount('Front Splits', currentUser.uid)>=10 },
      { name:'Side Splits (10 sessions)',                 check:()=>getExerciseSessionCount('Side Splits', currentUser.uid)>=10 },
      { name:'German Hang (10 sessions)',                 check:()=>getExerciseSessionCount('German Hang', currentUser.uid)>=10 },
      { name:'Pike Stretch (15 sessions)',                check:()=>getExerciseSessionCount('Pike Stretch', currentUser.uid)>=15 },
      { name:'Hip Mobility Routine (10 sessions)',        check:()=>getExerciseSessionCount('Hip Mobility Routine', currentUser.uid)>=10 },
      { name:'Yoga (20 sessions)',                        check:()=>getExerciseSessionCount('Yoga', currentUser.uid)>=20 },
      { name:'Pancake Stretch (10 sessions)',             check:()=>getExerciseSessionCount('Pancake Stretch', currentUser.uid)>=10 },
    ],
    title:'[Sovereign of Mobility]',
  },
  {
    id:'triathlete',
    name:'Triathlete',
    icon:'🚴',
    color:'#0EA5E9',
    desc:'Three disciplines. One relentless engine.',
    steps:[
      { name:'Run 10km',                           check:()=>myWorkouts.some(w=>w.runSummary?.distKm>=10) },
      { name:'Cycling (20 sessions)',              check:()=>['Cycling','Road Cycling','Mountain Biking','Stationary Bike','Spin Class','Cycling Intervals'].reduce((t,n)=>t+getExerciseSessionCount(n,currentUser.uid),0)>=20 },
      { name:'Freestyle Swimming (20 sessions)',   check:()=>getExerciseSessionCount('Freestyle Swimming', currentUser.uid)>=20 },
      { name:'Sub-60 min 10km',                   check:()=>{ const t=profile.bodyType==='female'?68:60; return myWorkouts.some(w=>{ const r=w.runSummary; return r&&r.distKm>=9.9&&r.durationMins<=t; }); }, label:()=>`Sub-${profile.bodyType==='female'?68:60} min 10km` },
      { name:'Cycling (50 sessions)',              check:()=>['Cycling','Road Cycling','Mountain Biking','Stationary Bike','Spin Class','Cycling Intervals'].reduce((t,n)=>t+getExerciseSessionCount(n,currentUser.uid),0)>=50 },
      { name:'Run half marathon (21km)',           check:()=>myWorkouts.some(w=>w.runSummary?.distKm>=21) },
    ],
    title:'[Triathlete]',
  },
  {
    id:'the_one_above_all',
    name:'The One Above All',
    icon:'👑',
    color:'#FFD700',
    desc:'You pursued everything. Speed. Strength. Skill. Endurance. Flexibility. Sport. The System has no rank for what you are.',
    steps:[
      { name:'Deadlift — elite level',             check:(bw)=>{ const m=profile.bodyType==='female'?2.0:2.75; return myPRs['Deadlift']?.e1rm >= bw*m; },        label:(bw)=>{ const m=profile.bodyType==='female'?2.0:2.75; return `Deadlift ${m}× bodyweight (${Math.round(bw*m)}kg e1RM)`; } },
      { name:'Bench Press — elite level',          check:(bw)=>{ const m=profile.bodyType==='female'?1.35:2.0; return myPRs['Bench Press']?.e1rm >= bw*m; },     label:(bw)=>{ const m=profile.bodyType==='female'?1.35:2.0; return `Bench Press ${m}× bodyweight (${Math.round(bw*m)}kg e1RM)`; } },
      { name:'Squat — elite level',                check:(bw)=>{ const m=profile.bodyType==='female'?1.75:2.25; return myPRs['Squat']?.e1rm >= bw*m; },          label:(bw)=>{ const m=profile.bodyType==='female'?1.75:2.25; return `Squat ${m}× bodyweight (${Math.round(bw*m)}kg e1RM)`; } },
      { name:'Overhead Press — elite level',       check:(bw)=>{ const m=profile.bodyType==='female'?0.85:1.25; return myPRs['Overhead Press']?.e1rm >= bw*m; },  label:(bw)=>{ const m=profile.bodyType==='female'?0.85:1.25; return `OHP ${m}× bodyweight (${Math.round(bw*m)}kg e1RM)`; } },
      { name:'Muscle Up (15 sessions)',             check:()=>getExerciseSessionCount('Muscle Up', currentUser.uid)>=15 },
      { name:'Full Planche (10 sessions)',          check:()=>getExerciseSessionCount('Full Planche', currentUser.uid)>=10 },
      { name:'Front Lever (10 sessions)',           check:()=>getExerciseSessionCount('Front Lever', currentUser.uid)>=10 },
      { name:'Handstand Push Up (10 sessions)',     check:()=>getExerciseSessionCount('Handstand Push Up', currentUser.uid)>=10 },
      { name:'Front Splits (10 sessions)',          check:()=>getExerciseSessionCount('Front Splits', currentUser.uid)>=10 },
      { name:'German Hang (10 sessions)',           check:()=>getExerciseSessionCount('German Hang', currentUser.uid)>=10 },
      { name:'Elite 5km time',                     check:()=>{ const t=profile.bodyType==='female'?25:22; return myWorkouts.some(w=>{ const r=w.runSummary; return r&&r.distKm>=4.9&&r.durationMins<=t; }); },  label:()=>`Sub-${profile.bodyType==='female'?25:22} min 5km` },
      { name:'Elite 10km time',                    check:()=>{ const t=profile.bodyType==='female'?52:45; return myWorkouts.some(w=>{ const r=w.runSummary; return r&&r.distKm>=9.9&&r.durationMins<=t; }); }, label:()=>`Sub-${profile.bodyType==='female'?52:45} min 10km` },
      { name:'Elite half marathon',                check:()=>{ const t=profile.bodyType==='female'?120:105; return myWorkouts.some(w=>{ const r=w.runSummary; return r&&r.distKm>=21&&r.durationMins<=t; }); }, label:()=>`Sub-${profile.bodyType==='female'?'2hr':'1hr 45min'} half marathon` },
      { name:'Boxing (50 sessions)',               check:()=>['Boxing — Bag Work','Boxing — Sparring','Boxing — Pad Work','Boxing — Shadow Boxing'].reduce((t,n)=>t+getExerciseSessionCount(n,currentUser.uid),0)>=50 },
      { name:'Court/Field sport (50 sessions)',    check:()=>['Tennis','Tennis Drills','Basketball','Basketball Drills','Football (Soccer)','Football Drills','American Football'].reduce((t,n)=>t+getExerciseSessionCount(n,currentUser.uid),0)>=50 },
      { name:'Swimming (30 sessions)',             check:()=>['Freestyle Swimming','Breaststroke Swimming','Butterfly Swimming','Backstroke Swimming','Open Water Swimming','HIIT Swimming'].reduce((t,n)=>t+getExerciseSessionCount(n,currentUser.uid),0)>=30 },
      { name:'Climbing (30 sessions)',             check:()=>['Bouldering','Sport Climbing','Top Rope Climbing','Traditional Climbing'].reduce((t,n)=>t+getExerciseSessionCount(n,currentUser.uid),0)>=30 },
      { name:'Cycling (30 sessions)',              check:()=>['Cycling','Road Cycling','Mountain Biking','Stationary Bike','Spin Class','Cycling Intervals'].reduce((t,n)=>t+getExerciseSessionCount(n,currentUser.uid),0)>=30 },
      { name:'365-day streak',                     check:()=>computeStreak(currentUser.uid)>=365 },
    ],
    title:'[The One Above All]',
  },
  ];
}
