// Base exercise library — muscle groups, equipment, bodyweight percentages, timed flags.
// Merged with each user's custom exercises at runtime (see rebuildExercisesAll in index.html).
export const BASE_EXERCISES = {
  "Bench Press": { muscles: { "Middle Chest": 1, "Triceps": 0.6, "Front Shoulders": 0.3 }, equipment: "Barbell" },
  "Incline Bench Press": { muscles: { "Upper Chest": 1, "Front Shoulders": 0.6, "Triceps": 0.3 }, equipment: "Barbell" },
  "Incline Dumbbell Press": { muscles: { "Upper Chest": 1, "Front Shoulders": 0.6, "Triceps": 0.3 }, equipment: "Dumbbell" },
  "Dumbbell Fly": { muscles: { "Middle Chest": 1, "Front Shoulders": 0.2 }, equipment: "Dumbbell" },
  "Push Up": { bwPercent: 0.67, muscles: { "Middle Chest": 1, "Triceps": 0.6, "Front Shoulders": 0.3 }, equipment: "Bodyweight" },
  "Dips": { bwPercent: 0.85, muscles: { "Lower Chest": 1, "Triceps": 0.6, "Front Shoulders": 0.3 }, equipment: "Bodyweight" },
  "Decline Bench Press": { muscles: { "Lower Chest": 1, "Triceps": 0.6, "Front Shoulders": 0.2 }, equipment: "Barbell" },
  "Decline Dumbbell Press": { muscles: { "Lower Chest": 1, "Triceps": 0.6, "Front Shoulders": 0.2 }, equipment: "Dumbbell" },
  "Incline Dumbbell Fly": { muscles: { "Upper Chest": 1, "Front Shoulders": 0.3 }, equipment: "Dumbbell" },
  "Decline Dumbbell Fly": { muscles: { "Lower Chest": 1, "Front Shoulders": 0.2 }, equipment: "Dumbbell" },
  "Cable Crossover": { muscles: { "Middle Chest": 1, "Front Shoulders": 0.2 }, equipment: "Cable" },
  "Cable Fly Low-to-High": { muscles: { "Upper Chest": 1, "Front Shoulders": 0.3 }, equipment: "Cable" },
  "Cable Fly High-to-Low": { muscles: { "Lower Chest": 1, "Front Shoulders": 0.2 }, equipment: "Cable" },
  "Pec Deck Machine": { muscles: { "Middle Chest": 1 }, equipment: "Machine" },
  "Svend Press": { muscles: { "Middle Chest": 1, "Front Shoulders": 0.2 }, equipment: "Dumbbell" },
  "Dumbbell Pullover": { muscles: { "Lats": 1, "Middle Chest": 0.3, "Triceps": 0.2 }, equipment: "Dumbbell" },
  "Incline Push Up": { bwPercent: 0.55, muscles: { "Lower Chest": 1, "Triceps": 0.3, "Front Shoulders": 0.2 }, equipment: "Bodyweight" },
  "Decline Push Up": { bwPercent: 0.75, muscles: { "Upper Chest": 1, "Front Shoulders": 0.6, "Triceps": 0.3 }, equipment: "Bodyweight" },
  "Diamond Push Up": { bwPercent: 0.75, muscles: { "Triceps": 1, "Middle Chest": 0.6, "Front Shoulders": 0.3 }, equipment: "Bodyweight" },
  "Wide Push Up": { bwPercent: 0.67, muscles: { "Middle Chest": 1, "Front Shoulders": 0.3 }, equipment: "Bodyweight" },
  "Archer Push Up": { bwPercent: 0.67, muscles: { "Middle Chest": 1, "Triceps": 0.6, "Front Shoulders": 0.3 }, equipment: "Bodyweight" },
  "Ring Dips": { bwPercent: 0.85, muscles: { "Lower Chest": 1, "Triceps": 0.6, "Front Shoulders": 0.3 }, equipment: "Bodyweight" },
  "Overhead Press": { muscles: { "Front Shoulders": 1, "Lateral Shoulders": 0.6, "Triceps": 0.6, "Upper Abs": 0.2 }, equipment: "Barbell" },
  "Lateral Raise": { muscles: { "Lateral Shoulders": 1, "Traps": 0.2 }, equipment: "Dumbbell" },
  "Front Raise": { muscles: { "Front Shoulders": 1, "Upper Chest": 0.2 }, equipment: "Dumbbell" },
  "Rear Delt Fly": { muscles: { "Rear Shoulders": 1, "Upper Back": 0.6, "Traps": 0.2 }, equipment: "Dumbbell" },
  "Arnold Press": { muscles: { "Front Shoulders": 1, "Lateral Shoulders": 0.6, "Triceps": 0.3 }, equipment: "Dumbbell" },
  "Dumbbell Shoulder Press": { muscles: { "Front Shoulders": 1, "Lateral Shoulders": 0.6, "Triceps": 0.6 }, equipment: "Dumbbell" },
  "Machine Shoulder Press": { muscles: { "Front Shoulders": 1, "Lateral Shoulders": 0.3, "Triceps": 0.6 }, equipment: "Machine" },
  "Push Press": { muscles: { "Front Shoulders": 1, "Lateral Shoulders": 0.6, "Triceps": 0.6, "Quads": 0.3, "Hip Flexors": 0.2 }, equipment: "Barbell" },
  "Cable Lateral Raise": { muscles: { "Lateral Shoulders": 1, "Traps": 0.2 }, equipment: "Cable" },
  "Plate Front Raise": { muscles: { "Front Shoulders": 1, "Upper Chest": 0.2, "Lateral Shoulders": 0.2 }, equipment: "Barbell" },
  "Upright Row": { muscles: { "Lateral Shoulders": 1, "Traps": 0.6, "Biceps": 0.2 }, equipment: "Barbell" },
  "Cuban Press": { muscles: { "Lateral Shoulders": 0.7, "Rear Shoulders": 0.7, "Front Shoulders": 0.4, "Traps": 0.2 }, equipment: "Dumbbell" },
  "Cable Rear Delt Fly": { muscles: { "Rear Shoulders": 1, "Upper Back": 0.3 }, equipment: "Cable" },
  "Face Pull": { muscles: { "Rear Shoulders": 1, "Upper Back": 0.6, "Traps": 0.3 }, equipment: "Cable" },
  "Reverse Pec Deck": { muscles: { "Rear Shoulders": 1, "Upper Back": 0.3 }, equipment: "Machine" },
  "Pike Push Up": { bwPercent: 0.7, muscles: { "Front Shoulders": 1, "Lateral Shoulders": 0.3, "Triceps": 0.6 }, equipment: "Bodyweight" },
  "Handstand Push Up": { bwPercent: 1.0, muscles: { "Front Shoulders": 1, "Lateral Shoulders": 0.6, "Triceps": 0.6 }, equipment: "Bodyweight" },
  "Wall Walk": { muscles: { "Front Shoulders": 1, "Upper Abs": 0.6, "Lats": 0.2 }, equipment: "Bodyweight" },
  "Deadlift": { muscles: { "Lower Back": 1, "Glutes": 1, "Hamstrings": 0.6, "Lats": 0.6, "Traps": 0.6, "Quads": 0.3, "Forearms": 0.3 }, equipment: "Barbell" },
  "Pull Up": { bwPercent: 1.0, muscles: { "Lats": 1, "Upper Back": 0.6, "Biceps": 0.6, "Forearms": 0.3 }, equipment: "Bodyweight" },
  "Lat Pulldown": { muscles: { "Lats": 1, "Upper Back": 0.3, "Biceps": 0.6 }, equipment: "Cable" },
  "Barbell Row": { muscles: { "Upper Back": 1, "Lats": 0.6, "Biceps": 0.6, "Traps": 0.3, "Lower Back": 0.2 }, equipment: "Barbell" },
  "Seated Cable Row": { muscles: { "Upper Back": 1, "Lats": 0.6, "Biceps": 0.6 }, equipment: "Cable" },
  "T-Bar Row": { muscles: { "Upper Back": 1, "Lats": 0.6, "Biceps": 0.6, "Lower Back": 0.2 }, equipment: "Machine" },
  "One-Arm Dumbbell Row": { muscles: { "Lats": 1, "Upper Back": 0.6, "Biceps": 0.6 }, equipment: "Dumbbell" },
  "Sumo Deadlift": { muscles: { "Glutes": 1, "Quads": 0.6, "Hamstrings": 0.6, "Lower Back": 0.4, "Traps": 0.3 }, equipment: "Barbell" },
  "Stiff-Leg Deadlift": { muscles: { "Hamstrings": 1, "Lower Back": 0.6, "Glutes": 0.3 }, equipment: "Barbell" },
  "Rack Pull": { muscles: { "Traps": 1, "Upper Back": 0.6, "Lower Back": 0.6, "Forearms": 0.3 }, equipment: "Barbell" },
  "Chin Up": { bwPercent: 1.0, muscles: { "Lats": 1, "Biceps": 1, "Upper Back": 0.3, "Forearms": 0.2 }, equipment: "Bodyweight" },
  "Wide Grip Pull Up": { bwPercent: 1.0, muscles: { "Lats": 1, "Upper Back": 0.6, "Biceps": 0.3 }, equipment: "Bodyweight" },
  "Neutral Grip Pull Up": { bwPercent: 1.0, muscles: { "Lats": 1, "Biceps": 0.6, "Upper Back": 0.3, "Forearms": 0.2 }, equipment: "Bodyweight" },
  "Commando Pull Up": { bwPercent: 1.0, muscles: { "Lats": 1, "Biceps": 0.6, "Upper Back": 0.3, "Obliques": 0.2 }, equipment: "Bodyweight" },
  "Muscle Up": { bwPercent: 1.0, muscles: { "Lats": 1, "Triceps": 1, "Upper Back": 0.6, "Biceps": 0.6, "Middle Chest": 0.3 }, equipment: "Bodyweight" },
  "Inverted Row": { bwPercent: 0.7, muscles: { "Upper Back": 1, "Lats": 0.6, "Biceps": 0.6, "Rear Shoulders": 0.3 }, equipment: "Bodyweight" },
  "Close Grip Lat Pulldown": { muscles: { "Lats": 1, "Biceps": 0.6, "Upper Back": 0.3 }, equipment: "Cable" },
  "Straight Arm Pulldown": { muscles: { "Lats": 1, "Triceps": 0.3 }, equipment: "Cable" },
  "Pendlay Row": { muscles: { "Upper Back": 1, "Lats": 0.6, "Biceps": 0.6, "Lower Back": 0.2 }, equipment: "Barbell" },
  "Chest Supported Row": { muscles: { "Upper Back": 1, "Lats": 0.3, "Biceps": 0.6, "Rear Shoulders": 0.3 }, equipment: "Machine" },
  "Meadows Row": { muscles: { "Lats": 1, "Upper Back": 0.6, "Biceps": 0.6 }, equipment: "Barbell" },
  "Good Morning": { muscles: { "Hamstrings": 1, "Lower Back": 1, "Glutes": 0.6 }, equipment: "Barbell" },
  "Back Extension": { muscles: { "Lower Back": 1, "Glutes": 0.6, "Hamstrings": 0.6 }, equipment: "Bodyweight" },
  "Superman": { muscles: { "Lower Back": 1, "Glutes": 0.6, "Rear Shoulders": 0.2 }, equipment: "Bodyweight" },
  "Dumbbell Shrugs": { muscles: { "Traps": 1, "Forearms": 0.2 }, equipment: "Dumbbell" },
  "Farmers Carry": { timed: true, muscles: { "Traps": 1, "Forearms": 1 }, equipment: "Dumbbell" },
  "Barbell Curl": { muscles: { "Biceps": 1, "Forearms": 0.3 }, equipment: "Barbell" },
  "Dumbbell Curl": { muscles: { "Biceps": 1, "Forearms": 0.3 }, equipment: "Dumbbell" },
  "Alternate Incline Dumbbell Curl": { muscles: { "Biceps": 1, "Forearms": 0.2 }, equipment: "Dumbbell" },
  "Hammer Curl": { muscles: { "Biceps": 0.6, "Forearms": 1 }, equipment: "Dumbbell" },
  "Preacher Curl": { muscles: { "Biceps": 1 }, equipment: "Barbell" },
  "EZ Bar Curl": { muscles: { "Biceps": 1, "Forearms": 0.3 }, equipment: "Barbell" },
  "Cable Curl": { muscles: { "Biceps": 1, "Forearms": 0.2 }, equipment: "Cable" },
  "Concentration Curl": { muscles: { "Biceps": 1 }, equipment: "Dumbbell" },
  "Spider Curl": { muscles: { "Biceps": 1 }, equipment: "Barbell" },
  "Zottman Curl": { muscles: { "Biceps": 0.6, "Forearms": 1 }, equipment: "Dumbbell" },
  "Tricep Pushdown": { muscles: { "Triceps": 1 }, equipment: "Cable" },
  "Skull Crusher": { muscles: { "Triceps": 1 }, equipment: "Barbell" },
  "Overhead Tricep Extension": { muscles: { "Triceps": 1 }, equipment: "Dumbbell" },
  "Close Grip Bench Press": { muscles: { "Triceps": 1, "Middle Chest": 0.6, "Front Shoulders": 0.3 }, equipment: "Barbell" },
  "Tricep Kickback": { muscles: { "Triceps": 1 }, equipment: "Dumbbell" },
  "JM Press": { muscles: { "Triceps": 1, "Middle Chest": 0.3 }, equipment: "Barbell" },
  "Bench Dip": { bwPercent: 0.75, muscles: { "Triceps": 1, "Lower Chest": 0.3, "Front Shoulders": 0.3 }, equipment: "Bodyweight" },
  "Wrist Curl": { muscles: { "Forearms": 1 }, equipment: "Dumbbell" },
  "Reverse Wrist Curl": { muscles: { "Forearms": 1 }, equipment: "Dumbbell" },
  "Dead Hang": { timed: true, bwPercent: 1.0, muscles: { "Forearms": 1, "Lats": 0.3 }, equipment: "Bodyweight" },
  "Scapula Push Up": { muscles: { "Traps": 0.6, "Upper Back": 1, "Rear Shoulders": 0.4 }, equipment: "Bodyweight" },
  "Scapular Push Up": { muscles: { "Traps": 0.6, "Upper Back": 1, "Rear Shoulders": 0.4 }, equipment: "Bodyweight" },
  "Scapula Pull Up": { muscles: { "Traps": 1, "Upper Back": 0.6, "Lats": 0.4 }, equipment: "Bodyweight" },
  "Crunch": { muscles: { "Upper Abs": 1 }, equipment: "Bodyweight" },
  "Plank": { timed: true, muscles: { "Upper Abs": 0.6, "Lower Abs": 0.6, "Obliques": 0.3, "Front Shoulders": 0.2 }, equipment: "Bodyweight" },
  "Hanging Leg Raise": { muscles: { "Lower Abs": 1, "Hip Flexors": 0.6, "Forearms": 0.2 }, equipment: "Bodyweight" },
  "Cable Crunch": { muscles: { "Upper Abs": 1, "Middle Abs": 0.3 }, equipment: "Cable" },
  "Russian Twist": { muscles: { "Obliques": 1, "Upper Abs": 0.3 }, equipment: "Bodyweight" },
  "Reverse Crunch": { muscles: { "Lower Abs": 1, "Hip Flexors": 0.3 }, equipment: "Bodyweight" },
  "Bicycle Crunch": { muscles: { "Obliques": 1, "Upper Abs": 0.6 }, equipment: "Bodyweight" },
  "Side Plank": { timed: true, muscles: { "Obliques": 1, "Lateral Shoulders": 0.2 }, equipment: "Bodyweight" },
  "Hanging Knee Raise": { muscles: { "Lower Abs": 1, "Hip Flexors": 0.6, "Forearms": 0.2 }, equipment: "Bodyweight" },
  "Toes to Bar": { muscles: { "Lower Abs": 1, "Hip Flexors": 0.6, "Forearms": 0.3 }, equipment: "Bodyweight" },
  "Cable Woodchopper": { muscles: { "Obliques": 1, "Upper Abs": 0.3, "Lats": 0.2 }, equipment: "Cable" },
  "V-Up": { muscles: { "Upper Abs": 1, "Lower Abs": 1, "Hip Flexors": 0.6 }, equipment: "Bodyweight" },
  "Mountain Climber": { timed: true, muscles: { "Lower Abs": 1, "Hip Flexors": 0.6, "Front Shoulders": 0.3 }, equipment: "Bodyweight" },
  "Ab Wheel Rollout": { muscles: { "Upper Abs": 1, "Lower Abs": 0.6, "Lats": 0.3, "Triceps": 0.2 }, equipment: "Bodyweight" },
  "Dragon Flag": { muscles: { "Lower Abs": 1, "Upper Abs": 0.6, "Hip Flexors": 0.3, "Lats": 0.2 }, equipment: "Bodyweight" },
  "Sit Up": { muscles: { "Upper Abs": 1, "Hip Flexors": 0.6, "Middle Abs": 0.3 }, equipment: "Bodyweight" },
  "Decline Sit Up": { muscles: { "Upper Abs": 1, "Hip Flexors": 0.6, "Middle Abs": 0.3 }, equipment: "Bodyweight" },
  "Flutter Kicks": { timed: true, muscles: { "Lower Abs": 1, "Hip Flexors": 0.6 }, equipment: "Bodyweight" },
  "L-Sit": { timed: true, muscles: { "Lower Abs": 1, "Hip Flexors": 1, "Triceps": 0.3, "Front Shoulders": 0.2 }, equipment: "Bodyweight" },
  "Lying Leg Raise": { muscles: { "Lower Abs": 1, "Hip Flexors": 0.6 }, equipment: "Bodyweight" },
  "Squat": { muscles: { "Quads": 1, "Glutes": 1, "Hamstrings": 0.3, "Lower Back": 0.2, "Hip Flexors": 0.2 }, equipment: "Barbell" },
  "Front Squat": { muscles: { "Quads": 1, "Glutes": 0.6, "Hip Flexors": 0.2, "Upper Back": 0.2 }, equipment: "Barbell" },
  "Leg Press": { muscles: { "Quads": 1, "Glutes": 0.6, "Hamstrings": 0.2 }, equipment: "Machine" },
  "Lunges": { bwPercent: 0.5, muscles: { "Quads": 1, "Glutes": 1, "Hamstrings": 0.3, "Hip Flexors": 0.2 }, equipment: "Dumbbell" },
  "Leg Extension": { muscles: { "Quads": 1 }, equipment: "Machine" },
  "Leg Curl": { muscles: { "Hamstrings": 1 }, equipment: "Machine" },
  "Romanian Deadlift": { muscles: { "Hamstrings": 1, "Glutes": 0.6, "Lower Back": 0.6 }, equipment: "Barbell" },
  "Hip Thrust": { muscles: { "Glutes": 1, "Hamstrings": 0.6 }, equipment: "Barbell" },
  "Calf Raise": { muscles: { "Calves": 1 }, equipment: "Machine" },
  "Hack Squat": { muscles: { "Quads": 1, "Glutes": 0.6, "Hamstrings": 0.2 }, equipment: "Machine" },
  "Bulgarian Split Squat": { muscles: { "Quads": 1, "Glutes": 1, "Hamstrings": 0.3, "Hip Flexors": 0.2 }, equipment: "Dumbbell" },
  "Goblet Squat": { muscles: { "Quads": 1, "Glutes": 0.6, "Upper Back": 0.2 }, equipment: "Dumbbell" },
  "Pistol Squat": { bwPercent: 0.72, muscles: { "Quads": 1, "Glutes": 0.6, "Hip Flexors": 0.3 }, equipment: "Bodyweight" },
  "Jump Squat": { bwPercent: 0.56, muscles: { "Quads": 1, "Glutes": 1, "Calves": 0.6 }, equipment: "Bodyweight" },
  "Wall Sit": { timed: true, muscles: { "Quads": 1, "Glutes": 0.3 }, equipment: "Bodyweight" },
  "Bodyweight Squat": { bwPercent: 0.56, muscles: { "Quads": 1, "Glutes": 0.6 }, equipment: "Bodyweight" },
  "Walking Lunge": { bwPercent: 0.5, muscles: { "Quads": 1, "Glutes": 1, "Hamstrings": 0.3, "Calves": 0.2 }, equipment: "Dumbbell" },
  "Reverse Lunge": { bwPercent: 0.5, muscles: { "Quads": 1, "Glutes": 1, "Hip Flexors": 0.2 }, equipment: "Dumbbell" },
  "Step Up": { bwPercent: 0.8, muscles: { "Quads": 1, "Glutes": 1, "Hamstrings": 0.2, "Hip Flexors": 0.2 }, equipment: "Dumbbell" },
  "Nordic Curl": { bwPercent: 0.8, muscles: { "Hamstrings": 1, "Lower Back": 0.3, "Glutes": 0.2 }, equipment: "Bodyweight" },
  "Glute Bridge": { bwPercent: 0.5, muscles: { "Glutes": 1, "Hamstrings": 0.6 }, equipment: "Bodyweight" },
  "Cable Kickback": { muscles: { "Glutes": 1, "Hamstrings": 0.3 }, equipment: "Cable" },
  "Seated Calf Raise": { muscles: { "Calves": 1 }, equipment: "Machine" },
  "Standing Calf Raise": { muscles: { "Calves": 1 }, equipment: "Machine" },
  "Donkey Calf Raise": { muscles: { "Calves": 1 }, equipment: "Machine" },
  "Single Leg Calf Raise": { muscles: { "Calves": 1 }, equipment: "Bodyweight" },
  "Burpee": { muscles: { "Quads": 0.6, "Glutes": 0.6, "Front Shoulders": 0.6, "Triceps": 0.3, "Upper Abs": 0.3 }, equipment: "Bodyweight" },
  "Bear Crawl": { timed: true, muscles: { "Front Shoulders": 0.6, "Upper Abs": 0.6, "Triceps": 0.3, "Hip Flexors": 0.3 }, equipment: "Bodyweight" },
  "Box Jump": { muscles: { "Quads": 1, "Glutes": 1, "Calves": 0.6 }, equipment: "Bodyweight" },

  /* ---- Running & cardio ---- */
  "Running": { timed: true, timedUnit: "mins", muscles: { "Quads": 0.6, "Hamstrings": 0.6, "Glutes": 0.6, "Calves": 1, "Hip Flexors": 0.3 }, equipment: "Bodyweight" },
  "Easy Run": { timed: true, timedUnit: "mins", muscles: { "Quads": 0.6, "Hamstrings": 0.6, "Glutes": 0.6, "Calves": 1, "Hip Flexors": 0.3 }, equipment: "Bodyweight" },
  "Tempo Run": { timed: true, timedUnit: "mins", muscles: { "Quads": 0.6, "Hamstrings": 0.6, "Glutes": 0.6, "Calves": 1, "Hip Flexors": 0.3 }, equipment: "Bodyweight" },
  "Long Run": { timed: true, timedUnit: "mins", muscles: { "Quads": 0.6, "Hamstrings": 0.6, "Glutes": 0.6, "Calves": 1, "Hip Flexors": 0.3 }, equipment: "Bodyweight" },
  "Race": { timed: true, timedUnit: "mins", muscles: { "Quads": 0.6, "Hamstrings": 0.6, "Glutes": 0.6, "Calves": 1, "Hip Flexors": 0.3 }, equipment: "Bodyweight" },
  "Sprinting": { muscles: { "Quads": 1, "Hamstrings": 1, "Glutes": 1, "Calves": 0.6, "Hip Flexors": 0.6 }, equipment: "Bodyweight" },
  "Interval Running": { timed: true, timedUnit: "mins", muscles: { "Quads": 0.6, "Hamstrings": 0.6, "Glutes": 0.6, "Calves": 1, "Hip Flexors": 0.3 }, equipment: "Bodyweight" },
  "Hill Sprints": { timed: true, timedUnit: "mins", muscles: { "Quads": 1, "Glutes": 1, "Hamstrings": 0.6, "Calves": 0.6, "Hip Flexors": 0.6 }, equipment: "Bodyweight" },
  "Treadmill Run": { timed: true, timedUnit: "mins", muscles: { "Quads": 0.6, "Hamstrings": 0.6, "Glutes": 0.6, "Calves": 1, "Hip Flexors": 0.3 }, equipment: "Machine" },
  "Stair Climb": { timed: true, timedUnit: "mins", muscles: { "Quads": 1, "Glutes": 1, "Calves": 0.6, "Hamstrings": 0.3 }, equipment: "Machine" },
  "Jump Rope": { timed: true, timedUnit: "mins", muscles: { "Calves": 1, "Quads": 0.3, "Front Shoulders": 0.2 }, equipment: "Bodyweight" },

  // ── Rock Climbing ──
  "Bouldering": { timed: true, timedUnit: "mins", muscles: { "Forearms": 1, "Lats": 0.9, "Upper Back": 0.7, "Biceps": 0.7, "Front Shoulders": 0.5, "Upper Abs": 0.4, "Quads": 0.3 }, equipment: "Bodyweight" },
  "Sport Climbing": { timed: true, timedUnit: "mins", muscles: { "Forearms": 1, "Lats": 0.9, "Upper Back": 0.6, "Biceps": 0.6, "Quads": 0.5, "Calves": 0.4, "Upper Abs": 0.3 }, equipment: "Bodyweight" },
  "Top Rope Climbing": { timed: true, timedUnit: "mins", muscles: { "Forearms": 0.9, "Lats": 0.8, "Upper Back": 0.6, "Biceps": 0.5, "Quads": 0.4, "Calves": 0.3 }, equipment: "Bodyweight" },
  "Traditional Climbing": { timed: true, timedUnit: "mins", muscles: { "Forearms": 1, "Lats": 0.9, "Upper Back": 0.7, "Biceps": 0.6, "Quads": 0.5, "Calves": 0.4, "Upper Abs": 0.3 }, equipment: "Bodyweight" },

  // ── Swimming ──
  "Freestyle Swimming": { timed: true, timedUnit: "mins", muscles: { "Lats": 1, "Front Shoulders": 0.9, "Triceps": 0.7, "Upper Back": 0.6, "Glutes": 0.4, "Quads": 0.3, "Calves": 0.3 }, equipment: "Bodyweight" },
  "Breaststroke Swimming": { timed: true, timedUnit: "mins", muscles: { "Front Shoulders": 0.9, "Lats": 0.7, "Quads": 0.7, "Inner Thighs": 0.6, "Triceps": 0.5, "Glutes": 0.4 }, equipment: "Bodyweight" },
  "Butterfly Swimming": { timed: true, timedUnit: "mins", muscles: { "Lats": 1, "Front Shoulders": 1, "Triceps": 0.8, "Upper Back": 0.7, "Glutes": 0.6, "Lower Back": 0.5, "Upper Abs": 0.5 }, equipment: "Bodyweight" },
  "Backstroke Swimming": { timed: true, timedUnit: "mins", muscles: { "Lats": 1, "Upper Back": 0.8, "Rear Shoulders": 0.7, "Biceps": 0.6, "Glutes": 0.4, "Quads": 0.3 }, equipment: "Bodyweight" },
  "Open Water Swimming": { timed: true, timedUnit: "mins", muscles: { "Lats": 1, "Front Shoulders": 0.8, "Upper Back": 0.6, "Triceps": 0.6, "Glutes": 0.4, "Quads": 0.3 }, equipment: "Bodyweight" },
  "HIIT Swimming": { timed: true, timedUnit: "mins", muscles: { "Lats": 1, "Front Shoulders": 1, "Triceps": 0.8, "Upper Back": 0.7, "Glutes": 0.5, "Quads": 0.4 }, equipment: "Bodyweight" },

  // ── Splits & Flexibility Training ──
  "German Hang": { timed: true, timedUnit: "secs", muscles: { "Front Shoulders": 1, "Biceps": 0.8, "Forearms": 0.6, "Upper Back": 0.5, "Chest": 0.4 }, equipment: "Bodyweight" },
  "German Hang Progression": { timed: true, timedUnit: "secs", muscles: { "Front Shoulders": 1, "Biceps": 0.9, "Forearms": 0.7, "Upper Back": 0.5, "Chest": 0.5 }, equipment: "Bodyweight" },
  "Front Splits": { timed: true, timedUnit: "secs", muscles: { "Hip Flexors": 1, "Hamstrings": 1, "Quads": 0.6, "Glutes": 0.4, "Inner Thighs": 0.3 }, equipment: "Bodyweight" },
  "Side Splits": { timed: true, timedUnit: "secs", muscles: { "Inner Thighs": 1, "Hip Flexors": 0.8, "Hamstrings": 0.7, "Glutes": 0.4 }, equipment: "Bodyweight" },
  "Middle Splits": { timed: true, timedUnit: "secs", muscles: { "Inner Thighs": 1, "Hip Flexors": 0.9, "Hamstrings": 0.6, "Glutes": 0.3 }, equipment: "Bodyweight" },
  "Pike Stretch": { timed: true, timedUnit: "secs", muscles: { "Hamstrings": 1, "Lower Back": 0.5, "Calves": 0.4 }, equipment: "Bodyweight" },
  "Hip Flexor Stretch": { timed: true, timedUnit: "secs", muscles: { "Hip Flexors": 1, "Quads": 0.5, "Glutes": 0.3 }, equipment: "Bodyweight" },
  "Pancake Stretch": { timed: true, timedUnit: "secs", muscles: { "Inner Thighs": 1, "Hamstrings": 0.9, "Lower Back": 0.4 }, equipment: "Bodyweight" },
  "Shoulder Flexibility Training": { timed: true, timedUnit: "secs", muscles: { "Front Shoulders": 0.8, "Rear Shoulders": 0.8, "Triceps": 0.4, "Upper Back": 0.4 }, equipment: "Bodyweight" },
  "Thoracic Mobility": { timed: true, timedUnit: "secs", muscles: { "Upper Back": 1, "Rear Shoulders": 0.6, "Lower Back": 0.4 }, equipment: "Bodyweight" },
  "Hip Mobility Routine": { timed: true, timedUnit: "mins", muscles: { "Hip Flexors": 1, "Inner Thighs": 0.8, "Glutes": 0.6, "Hamstrings": 0.5 }, equipment: "Bodyweight" },
  "Full Body Stretching": { timed: true, timedUnit: "mins", muscles: { "Hamstrings": 0.6, "Hip Flexors": 0.6, "Inner Thighs": 0.5, "Upper Back": 0.5, "Front Shoulders": 0.4, "Calves": 0.4 }, equipment: "Bodyweight" },
  "Yoga": { timed: true, timedUnit: "mins", muscles: { "Hip Flexors": 0.8, "Hamstrings": 0.7, "Upper Back": 0.6, "Inner Thighs": 0.6, "Front Shoulders": 0.5, "Lower Back": 0.5 }, equipment: "Bodyweight" },

  // ── Cycling ──
  "Cycling": { timed: true, timedUnit: "mins", muscles: { "Quads": 1, "Hamstrings": 0.7, "Glutes": 0.8, "Calves": 0.7, "Hip Flexors": 0.4 }, equipment: "Bodyweight" },
  "Road Cycling": { timed: true, timedUnit: "mins", muscles: { "Quads": 1, "Hamstrings": 0.7, "Glutes": 0.8, "Calves": 0.7, "Hip Flexors": 0.4 }, equipment: "Bodyweight" },
  "Mountain Biking": { timed: true, timedUnit: "mins", muscles: { "Quads": 1, "Hamstrings": 0.7, "Glutes": 0.8, "Calves": 0.6, "Upper Back": 0.4, "Front Shoulders": 0.4, "Forearms": 0.5, "Upper Abs": 0.3 }, equipment: "Bodyweight" },
  "Stationary Bike": { timed: true, timedUnit: "mins", muscles: { "Quads": 1, "Hamstrings": 0.6, "Glutes": 0.7, "Calves": 0.6, "Hip Flexors": 0.3 }, equipment: "Machine" },
  "Spin Class": { timed: true, timedUnit: "mins", muscles: { "Quads": 1, "Hamstrings": 0.7, "Glutes": 0.8, "Calves": 0.6, "Hip Flexors": 0.4 }, equipment: "Machine" },
  "Cycling Intervals": { timed: true, timedUnit: "mins", muscles: { "Quads": 1, "Hamstrings": 0.8, "Glutes": 0.8, "Calves": 0.6, "Hip Flexors": 0.4 }, equipment: "Bodyweight" },
  "Tennis": { timed: true, timedUnit: "mins", muscles: { "Forearms": 1, "Front Shoulders": 0.8, "Lateral Shoulders": 0.6, "Obliques": 0.7, "Quads": 0.6, "Calves": 0.6, "Upper Back": 0.4 }, equipment: "Bodyweight" },
  "Tennis Drills": { timed: true, timedUnit: "mins", muscles: { "Forearms": 0.9, "Front Shoulders": 0.7, "Obliques": 0.6, "Quads": 0.7, "Calves": 0.6, "Hip Flexors": 0.4 }, equipment: "Bodyweight" },

  // ── Football ──
  "Football (Soccer)": { timed: true, timedUnit: "mins", muscles: { "Quads": 1, "Hamstrings": 0.9, "Calves": 0.8, "Glutes": 0.6, "Hip Flexors": 0.5, "Upper Abs": 0.2 }, equipment: "Bodyweight" },
  "Football Drills": { timed: true, timedUnit: "mins", muscles: { "Quads": 1, "Hamstrings": 0.8, "Calves": 0.7, "Glutes": 0.5, "Hip Flexors": 0.6 }, equipment: "Bodyweight" },
  "American Football": { timed: true, timedUnit: "mins", muscles: { "Quads": 1, "Hamstrings": 0.8, "Glutes": 0.7, "Front Shoulders": 0.5, "Upper Back": 0.5, "Triceps": 0.4, "Calves": 0.5 }, equipment: "Bodyweight" },

  // ── Basketball ──
  "Basketball": { timed: true, timedUnit: "mins", muscles: { "Quads": 1, "Calves": 0.9, "Glutes": 0.7, "Hamstrings": 0.6, "Front Shoulders": 0.4, "Forearms": 0.3, "Upper Abs": 0.3 }, equipment: "Bodyweight" },
  "Basketball Drills": { timed: true, timedUnit: "mins", muscles: { "Quads": 1, "Calves": 0.8, "Glutes": 0.6, "Hamstrings": 0.5, "Hip Flexors": 0.5, "Front Shoulders": 0.3 }, equipment: "Bodyweight" },

  // ── Boxing ──
  "Boxing — Bag Work": { timed: true, timedUnit: "mins", muscles: { "Front Shoulders": 1, "Triceps": 0.8, "Obliques": 0.8, "Upper Abs": 0.7, "Forearms": 0.7, "Quads": 0.4, "Calves": 0.4 }, equipment: "Bodyweight" },
  "Boxing — Sparring": { timed: true, timedUnit: "mins", muscles: { "Front Shoulders": 1, "Triceps": 0.8, "Obliques": 0.8, "Upper Abs": 0.7, "Forearms": 0.7, "Quads": 0.5, "Calves": 0.5, "Hip Flexors": 0.4 }, equipment: "Bodyweight" },
  "Boxing — Shadow Boxing": { timed: true, timedUnit: "mins", muscles: { "Front Shoulders": 0.9, "Triceps": 0.7, "Obliques": 0.7, "Upper Abs": 0.6, "Forearms": 0.5, "Quads": 0.3, "Calves": 0.3 }, equipment: "Bodyweight" },
  "Boxing — Pad Work": { timed: true, timedUnit: "mins", muscles: { "Front Shoulders": 1, "Triceps": 0.9, "Obliques": 0.8, "Upper Abs": 0.7, "Forearms": 0.8, "Quads": 0.4, "Calves": 0.4 }, equipment: "Bodyweight" },
  "Tuck Front Lever": { timed: true, bwPercent: 1.00, muscles: { "Lats": 1, "Upper Abs": 0.6, "Biceps": 0.3, "Forearms": 0.3 }, equipment: "Bodyweight" },
  "Advanced Tuck Front Lever": { timed: true, bwPercent: 1.00, muscles: { "Lats": 1, "Upper Abs": 0.6, "Lower Abs": 0.3, "Biceps": 0.3, "Forearms": 0.3 }, equipment: "Bodyweight" },
  "Single Leg Front Lever": { timed: true, bwPercent: 1.00, muscles: { "Lats": 1, "Lower Abs": 0.6, "Upper Abs": 0.6, "Biceps": 0.3, "Forearms": 0.3 }, equipment: "Bodyweight" },
  "Straddle Front Lever": { timed: true, bwPercent: 1.00, muscles: { "Lats": 1, "Lower Abs": 0.6, "Upper Abs": 0.6, "Biceps": 0.3, "Forearms": 0.3 }, equipment: "Bodyweight" },
  "Front Lever": { timed: true, bwPercent: 1.00, muscles: { "Lats": 1, "Lower Abs": 1, "Upper Abs": 0.6, "Biceps": 0.3, "Forearms": 0.6 }, equipment: "Bodyweight" },
  "Front Lever Row": { muscles: { "Lats": 1, "Upper Back": 0.6, "Biceps": 0.6 }, equipment: "Bodyweight" },
  "Front Lever Raise": { muscles: { "Lats": 1, "Lower Abs": 0.6, "Upper Abs": 0.6 }, equipment: "Bodyweight" },
  "Ice Cream Makers": { muscles: { "Lats": 1, "Upper Abs": 0.6, "Triceps": 0.3 }, equipment: "Bodyweight" },
  "Skin The Cat": { timed: true, muscles: { "Lats": 0.6, "Front Shoulders": 0.6, "Upper Abs": 0.3, "Biceps": 0.3 }, equipment: "Bodyweight" },
  "Wall Handstand Hold": { timed: true, muscles: { "Front Shoulders": 1, "Lateral Shoulders": 0.6, "Triceps": 0.2, "Upper Abs": 0.3, "Forearms": 0.2 }, equipment: "Bodyweight" },
  "Freestanding Handstand Hold": { timed: true, muscles: { "Front Shoulders": 1, "Lateral Shoulders": 0.6, "Upper Abs": 0.6, "Forearms": 0.3 }, equipment: "Bodyweight" },
  "Chest-to-Wall Handstand Hold": { timed: true, muscles: { "Front Shoulders": 1, "Lateral Shoulders": 0.3, "Upper Abs": 0.6, "Lower Back": 0.2 }, equipment: "Bodyweight" },
  "Handstand Shoulder Taps": { timed: true, muscles: { "Front Shoulders": 1, "Lateral Shoulders": 0.6, "Upper Abs": 0.6, "Obliques": 0.3 }, equipment: "Bodyweight" },
  "Deficit Handstand Push Up": { bwPercent: 1.0, muscles: { "Front Shoulders": 1, "Lateral Shoulders": 0.6, "Triceps": 1 }, equipment: "Bodyweight" },
  "Handstand Push Up Negative": { bwPercent: 1.0, muscles: { "Front Shoulders": 1, "Lateral Shoulders": 0.6, "Triceps": 0.6 }, equipment: "Bodyweight" },
  "Frog Stand": { timed: true, muscles: { "Front Shoulders": 1, "Upper Abs": 0.6, "Forearms": 0.3, "Triceps": 0.3 }, equipment: "Bodyweight" },
  "Tuck Planche": { timed: true, bwPercent: 1.00, muscles: { "Front Shoulders": 1, "Lower Abs": 0.6, "Middle Chest": 0.3, "Triceps": 0.6, "Forearms": 0.3 }, equipment: "Bodyweight" },
  "Advanced Tuck Planche": { timed: true, bwPercent: 1.00, muscles: { "Front Shoulders": 1, "Lower Abs": 0.6, "Middle Chest": 0.3, "Triceps": 0.6, "Forearms": 0.3 }, equipment: "Bodyweight" },
  "Straddle Planche": { timed: true, bwPercent: 1.00, muscles: { "Front Shoulders": 1, "Lower Abs": 0.6, "Middle Chest": 0.6, "Triceps": 0.6, "Forearms": 0.6 }, equipment: "Bodyweight" },
  "Full Planche": { timed: true, bwPercent: 1.00, muscles: { "Front Shoulders": 1, "Lower Abs": 0.6, "Middle Chest": 0.6, "Triceps": 0.6, "Forearms": 0.6 }, equipment: "Bodyweight" },
  "Planche Lean": { timed: true, bwPercent: 1.00, muscles: { "Front Shoulders": 1, "Middle Chest": 0.6, "Forearms": 0.6, "Lower Abs": 0.3 }, equipment: "Bodyweight" },
  "Planche Push Up": { muscles: { "Front Shoulders": 1, "Middle Chest": 0.6, "Triceps": 0.6 }, equipment: "Bodyweight" },
};
